### ISSUE TITLE
Route offset bug on MapView 

### ISSUE THREAD

**Issue by dieterbeelaert** [oSoc14/Artoria#24]
The droid OSM has a bug with lat, long offsets, this needs to be analysed and a preliminary offset fix will probably solve this issue.

https://github.com/osmdroid/osmdroid/issues/22

**Comment by coreation** [comment]
I'm not joking around with how issues are being formed @dieterbeelaert . Form good titles, good descriptions in a proper sentence. Another example:

[Title] Route offset bug on MapView -> viewer of an issue list has an immediate notion of what the issue is about

[Description]

The droid OSM has a bug with lat, long offsets, this needs to be analysed and a preliminary offset fix will probably solve this issue. [Link to known issue with droid OSM].

But an A+ on commitment to the project though ;)

**Comment by dieterbeelaert** [comment]
@coreation  Sorry, about that, I think it's hard to name issues, I'll work on it  :-)

**Comment by coreation** [comment]
No problem, again, great spirit and commitment, that way you'll have a killer presentation at the end of the 3 weeks and have an app that actually works on Android. Just think of the title as a sentence that captures the nature of the issue (that's only displayed on the issue list overview, without the description) and the description as a sufficient context provision of the issue.
